web:
  image: srod/nginx
  ports:
    - "8080:80"
  links:
    - php
  volumes:
    - "./app:/usr/share/nginx/html"
php:
  image: srod/php-fpm
  links:
    - db
  volumes:
    - "./app:/usr/share/nginx/html"
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
